/** Resource limits shared by normalization consumers and the sanitizer. */

/** Hard resource limits enforced by GenUI repair and rendering. */
export const GENUI_LIMITS = {
  maxDepth: 8,
  maxNodes: 200,
  maxString: 2000,
  maxCode: 12_000,
  maxMermaid: 8000,
  maxGridCols: 12,
  maxTabs: 12,
  maxAccordionItems: 24,
  maxListItems: 50,
  maxOptions: 50,
  maxTableRows: 50,
  maxTableCols: 12,
  maxChartPoints: 60,
  maxPlotSeries: 8,
  maxPlotParams: 6,
  maxMeshes: 5,
  maxQuizOptions: 8,
  maxSteps: 24,
  maxTimelineItems: 24,
  maxBreadcrumbItems: 12,
  maxKeyValuePairs: 24,
  maxTreeDepth: 6,
  maxDiagramNodes: 9,
  maxDiagramEdges: 12,
  maxDiagramZones: 3,
  maxDiagramFocal: 2,
  maxDiagramLabel: 14,
  maxEChartOptionDepth: 10,
  maxEChartArrayLen: 500,
  maxEChartOptionNodes: 2000,
} as const
